import { Geist, Geist_Mono, Poppins } from "next/font/google";
import { AuthProvider } from "../context/AuthContext";
import "./globals.css";
import Navbar from "./components/Navbar";
import { UserProfileProvider } from "../context/UserProfileContext";
import ReduxProvider from "@/redux/ReduxProvider";
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Faltu Fashion",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${poppins.variable}`}>
      <body
        className={`font-poppins antialiased text-gray-900`}
      >
        <AuthProvider>
          <UserProfileProvider>
            <ReduxProvider>
              <Navbar />
              {children}
            </ReduxProvider>
          </UserProfileProvider>
        </AuthProvider>
      </body>
    </html>
  );
}